version: "3.6"
services:
  grafana:
    image: "grafana/grafana:main"
    ports:
      - "3456:3000/tcp"
    restart: "unless-stopped"
    volumes:
      - "grafana-storage:/var/lib/grafana"

volumes:
  grafana-storage:
    external: true
