version: "3.6"
services:
  heimdall:
    image: "ghcr.io/linuxserver/heimdall:latest"
    ports:
      - "447:443/tcp"
      - "8002:80/tcp"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/heimdall:/config"
      - "/home/pi/storage:/storage"
