version: "3.6"
services:
  plex:
    image: "ghcr.io/linuxserver/plex:latest"
    ports:
      - "1900:1900/udp"
      - "3005:3005/tcp"
      - "32400:32400/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469/tcp"
      - "33400:33400/tcp"
      - "8324:8324/tcp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/plex:/config"
      - "/home/pi/storage:/storage"
      - "/mnt/nas/Media:/data"
    restart: "unless-stopped"
