version: "3.6"
services:
  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9200:9090/tcp"
    restart: "unless-stopped"
    volumes:
      - "/home/pi/.config/appdata/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-storage:/prometheus"

volumes:
  prometheus-storage:
    external: true
