version: "3.6"
services:
  transmission:
    image: "ghcr.io/linuxserver/transmission:latest"
    ports:
      - "51413:51413/tcp"
      - "51413:51413/udp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "9091:9091/tcp"
    restart: "unless-stopped"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/transmission:/config"
      - "/home/pi/storage:/storage"
      - "/mnt/nas/Public/Downloads/watch:/watch"
      - "/mnt/nas/Public/Downloads:/downloads"
