rpi_servers:
  hosts:
    atlaspi:
      ansible_host: 192.168.4.201
    pihole:
      ansible_host: 192.168.4.202
    retropi:
      ansible_host: 192.168.4.151
  vars:
    ansible_ssh_user: pi

ubuntu_servers:
  hosts:
    prometheus:
      ansible_host: prometheus.local
  vars:
    ansible_ssh_user: BigBrother

macos_servers:
  hosts:
    sisyphus:
      ansible_host: sisyphus.local
  vars:
    ansible_ssh_user: admin

rpi_build:
  hosts:
    test_bed:
      ansible_host: raspberrypi.local
  vars:
    ansible_ssh_user: pi

all_pi:
  children:
    rpi_servers:
    rpi_build:

prod_servers:
  children:
    rpi_servers:
    ubuntu_servers:
