version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/nas/Media/Audiobooks:/audiobooks
      - /mnt/nas/Media/Podcasts:/podcasts
      - /home/pi/.config/appdata/audiobookshelf:/config
      - /home/pi/.config/metadata/audiobookshelf:/metadata