version: "3.6"
services:
  calibreweb:
    image: "ghcr.io/linuxserver/calibre-web:latest"
    ports:
      - "8083:8083/tcp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/calibreweb:/config"
      - "/home/pi/storage:/storage"
      - "/mnt/nas/Media/Calibre Library:/books"
    restart: "unless-stopped"
