networks:
  compose_default:
    external: true
    name: "compose_default"

services:
  calibreweb:

    container_name: "calibreweb"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=Europe/London"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "LSIO_FIRST_PARTY=true"

    hostname: "atlaspi"

    image: "ghcr.io/linuxserver/calibre-web:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 0.6.11-ls114 Build-date:- 2021-04-13T11:19:32+01:00"
      com.docker.compose.config-hash: "99e6857d6842164083eb54b5eb31fcfdc81e7cfb3a78bf04d04a715619be6a78"
      com.docker.compose.container-number: "1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "compose"
      com.docker.compose.project.config_files: "docker-compose.yml,docker-compose.override.yml"
      com.docker.compose.project.working_dir: "/home/pi/.docker/compose"
      com.docker.compose.service: "calibreweb"
      com.docker.compose.version: "1.28.0"
      maintainer: "chbmb"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-04-08T20:48:13-05:00"
      org.opencontainers.image.description: "[Calibre-web](https://github.com/janeczku/calibre-web) is\
        \ a web app providing a clean interface for browsing, reading and downloading eBooks using an\
        \ existing Calibre database.   It is also possible to integrate google drive and edit metadata\
        \ and your calibre library through the app itself.    This software is a fork of library and licensed\
        \ under the GPL v3 License.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-calibre-web"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "a599958f6b4704aa478b58a2ebf9eed4af5c7f77"
      org.opencontainers.image.revision: "a599958f6b4704aa478b58a2ebf9eed4af5c7f77"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-calibre-web"
      org.opencontainers.image.title: "Calibre-web"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-calibre-web/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "0.6.20-ls204"

    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

    networks:
      - "compose_default"

    ports:
      - "8083:8083/tcp"

    restart: "unless-stopped"

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/calibreweb:/config"
      - "/home/pi/storage:/storage"
      - "/mnt/nas/Media/Calibre Library:/books"

    working_dir: "/"

version: "3.6"
