version: "3.6"
services:
  jellyfin:
    image: "lscr.io/linuxserver/jellyfin:latest"
    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"
    restart: "unless-stopped"
    volumes:
      - "/mnt/nas/Media:/media"
      - "/home/pi/.config/appdata/Jelllyfin:/config"
      - "/home/pi/.config/appdata/Jelllyfin/Movies:/data/movies"
      - "/home/pi/.config/appdata/Jelllyfin/TV:/data/tvshows"
