networks:
  compose_default:
    external: true
    name: "compose_default"

services:

  calibreweb:

    container_name: "calibreweb"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=Europe/London"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "LSIO_FIRST_PARTY=true"

    hostname: "atlaspi"

    image: "ghcr.io/linuxserver/calibre-web:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 0.6.11-ls114 Build-date:- 2021-04-13T11:19:32+01:00"
      com.docker.compose.config-hash: "99e6857d6842164083eb54b5eb31fcfdc81e7cfb3a78bf04d04a715619be6a78"
      com.docker.compose.container-number: "1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "compose"
      com.docker.compose.project.config_files: "docker-compose.yml,docker-compose.override.yml"
      com.docker.compose.project.working_dir: "/home/pi/.docker/compose"
      com.docker.compose.service: "calibreweb"
      com.docker.compose.version: "1.28.0"
      maintainer: "chbmb"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-04-08T20:48:13-05:00"
      org.opencontainers.image.description: "[Calibre-web](https://github.com/janeczku/calibre-web) is\
        \ a web app providing a clean interface for browsing, reading and downloading eBooks using an\
        \ existing Calibre database.   It is also possible to integrate google drive and edit metadata\
        \ and your calibre library through the app itself.    This software is a fork of library and licensed\
        \ under the GPL v3 License.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-calibre-web"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "a599958f6b4704aa478b58a2ebf9eed4af5c7f77"
      org.opencontainers.image.revision: "a599958f6b4704aa478b58a2ebf9eed4af5c7f77"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-calibre-web"
      org.opencontainers.image.title: "Calibre-web"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-calibre-web/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "0.6.20-ls204"

    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

    networks:
      - "compose_default"

    ports:
      - "8083:8083/tcp"

    restart: "unless-stopped"

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/calibreweb:/config"
      - "/home/pi/storage:/storage"
      - "/mnt/nas/Media/Calibre Library:/books"

    working_dir: "/"

  jellyfin:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "jellyfin"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=100"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"

    hostname: "bb7f7bd15997"

    image: "lscr.io/linuxserver/jellyfin:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 10.8.10-1-ls216 Build-date:- 2023-06-20T12:48:17+00:00"
      maintainer: "thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-06-20T12:48:17+00:00"
      org.opencontainers.image.description: "[Jellyfin](https://jellyfin.github.io/) is a Free Software\
        \ Media System that puts you in control of managing and streaming your media. It is an alternative\
        \ to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices\
        \ via multiple apps. Jellyfin is descended from Emby's 3.5.2 release and ported to the .NET Core\
        \ framework to enable full cross-platform support. There are no strings attached, no premium licenses\
        \ or features, and no hidden agendas: just a team who want to build something better and work\
        \ together to achieve it."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-jellyfin"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "83ee5ddbe1a03f04219f4d6cf8b41431de30619d"
      org.opencontainers.image.revision: "83ee5ddbe1a03f04219f4d6cf8b41431de30619d"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-jellyfin"
      org.opencontainers.image.title: "Jellyfin"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-jellyfin/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "10.8.10-1-ls216"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "02:42:ac:11:00:04"

    network_mode: "bridge"

    ports:
      - "8096:8096/tcp"
      - "8920:8920/tcp"

    restart: "unless-stopped"

    volumes:
      - "/mnt/nas/Media:/media"
      - "/portainer/Files/AppData/Config/Jelllyfin:/config"
      - "/portainer/Movies:/data/movies"
      - "/portainer/TV:/data/tvshows"

    working_dir: "/"

  plex:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "plex"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "PLEX_CLAIM=claim-zbQXfjLdiMV1pJG7NyHc"
      - "PUID=1000"
      - "TZ=Europe/London"
      - "VERSION=docker"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "DEBIAN_FRONTEND=noninteractive"
      - "PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server-new"
      - "PLEX_ARCH=armhf"
      - "PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support"
      - "PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver"
      - "PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6"
      - "PLEX_MEDIA_SERVER_USER=abc"
      - "PLEX_MEDIA_SERVER_INFO_VENDOR=Docker"
      - "PLEX_MEDIA_SERVER_INFO_DEVICE=Docker Container (LinuxServer.io)"

    hostname: "atlaspi"

    image: "ghcr.io/linuxserver/plex:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 1.23.1.4602-280ab6053-ls36 Build-date:- 2021-06-04T17:02:50+00:00"
      com.docker.compose.config-hash: "bb24474fd2da8cd9516ec799ef0b69f13bef95c4770d3248bb5dc7ac0be91ea8"
      com.docker.compose.container-number: "1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "compose"
      com.docker.compose.project.config_files: "docker-compose.yml,docker-compose.override.yml"
      com.docker.compose.project.working_dir: "/home/pi/.docker/compose"
      com.docker.compose.service: "plex"
      com.docker.compose.version: "1.28.0"
      maintainer: "thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2021-06-04T17:02:50+00:00"
      org.opencontainers.image.description: "[Plex](https://plex.tv) organizes video, music and photos\
        \ from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices.\
        \ This container is packaged as a standalone Plex Media Server. has always been a top priority.\
        \ Straightforward design and bulk actions mean getting things done faster."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-plex"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "cea77a92aa1821b93a2e14b0d56a2f8d68c878ce"
      org.opencontainers.image.revision: "cea77a92aa1821b93a2e14b0d56a2f8d68c878ce"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-plex"
      org.opencontainers.image.title: "Plex"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-plex/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "1.23.1.4602-280ab6053-ls36"

    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

    networks:
      - "compose_default"

    ports:
      - "1900:1900/udp"
      - "3005:3005/tcp"
      - "32400:32400/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469/tcp"
      - "33400:33400/tcp"
      - "8324:8324/tcp"

    restart: "unless-stopped"

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/plex:/config"
      - "/home/pi/storage:/storage"
      - "/mnt/nas/Media:/data"

    working_dir: "/"

  tautulli:

    container_name: "tautulli"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "TAUTULLI_DOCKER=True"

    hostname: "ab33be70bdea"

    image: "linuxserver/tautulli:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v2.6.10-ls6 Build-date:- 2021-04-09T03:38:17+00:00"
      maintainer: "nemchik,thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2021-11-19T04:31:55+01:00"
      org.opencontainers.image.description: "[Tautulli](http://tautulli.com) is a python based web application\
        \ for monitoring, analytics and notifications for Plex Media Server."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-tautulli"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "55c1f8ad6525d599b1f997562c5b44b1a3bfff2b"
      org.opencontainers.image.revision: "55c1f8ad6525d599b1f997562c5b44b1a3bfff2b"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-tautulli"
      org.opencontainers.image.title: "Tautulli"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-tautulli/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v2.7.7-ls24"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "02:42:ac:11:00:02"

    network_mode: "bridge"

    ports:
      - "8181:8181/tcp"

    restart: "unless-stopped"

    volumes:
      - "7443edbff9bec1ebf4400e3cb0c9dd35be3c43ed1f55b535c4664da3c1a96d94:/config"
      - "c06958ff1e5f517d065e5b25bed1c2cc002d69c0f4289c5212d8805091ca8029:/logs"

    working_dir: "/"

version: "3.6"

volumes:
  7443edbff9bec1ebf4400e3cb0c9dd35be3c43ed1f55b535c4664da3c1a96d94:
    external: true
  c06958ff1e5f517d065e5b25bed1c2cc002d69c0f4289c5212d8805091ca8029:
    external: true