services:
  prometheus:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

    container_name: "prometheus"

    entrypoint:
      - "/bin/prometheus"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    hostname: "f04576a0edd2"

    image: "prom/prometheus:latest"

    ipc: "private"

    labels:
      maintainer: "The Prometheus Authors <prometheus-developers@googlegroups.com>"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "02:42:ac:11:00:06"

    network_mode: "bridge"

    ports:
      - "9200:9090/tcp"

    restart: "unless-stopped"

    user: "nobody"

    volumes:
      - "/home/pi/.config/appdata/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-storage:/prometheus"

    working_dir: "/prometheus"

version: "3.6"

volumes:
  prometheus-storage:
    external: true
