networks:
  compose_default:
    external: true
    name: "compose_default"

services:

  heimdall:

    container_name: "heimdall"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=Europe/London"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"

    hostname: "atlaspi"

    image: "ghcr.io/linuxserver/heimdall:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v2.5.6-ls217 Build-date:- 2023-05-26T18:32:44+00:00"
      com.docker.compose.config-hash: "7ae37d209b374659dfd08e335b3d4db53279585f753fcc6bad9c75649435270f"
      com.docker.compose.container-number: "1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "compose"
      com.docker.compose.project.config_files: "docker-compose.yml,docker-compose.override.yml"
      com.docker.compose.project.working_dir: "/home/pi/.docker/compose"
      com.docker.compose.service: "heimdall"
      com.docker.compose.version: "1.28.0"
      maintainer: "aptalca"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-05-26T18:32:44+00:00"
      org.opencontainers.image.description: "[Heimdall](https://heimdall.site) is a way to organise all\
        \ those links to your most used web sites and web applications in a simple way.    Simplicity\
        \ is the key to Heimdall.    Why not use it as your browser start page? It even has the ability\
        \ to include a search bar using either Google, Bing or DuckDuckGo.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-heimdall"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "1d14a698e90b8ecf03c0badebcb01c4646bf92b6"
      org.opencontainers.image.revision: "1d14a698e90b8ecf03c0badebcb01c4646bf92b6"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-heimdall"
      org.opencontainers.image.title: "Heimdall"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-heimdall/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v2.5.6-ls217"

    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

    networks:
      - "compose_default"

    ports:
      - "447:443/tcp"
      - "8002:80/tcp"

    restart: "unless-stopped"

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/heimdall:/config"
      - "/home/pi/storage:/storage"

    working_dir: "/"

  homebridge:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "homebridge"

    entrypoint:
      - "/init"

    environment:
      - "CONFIG_UI_VERSION=4.45.0"
      - "ENABLE_AVAHI=0"
      - "HOMEBRIDGE_CONFIG_UI=1"
      - "HOMEBRIDGE_CONFIG_UI_PORT=8581"
      - "HOMEBRIDGE_VERSION=1.4.1"
      - "NODE_VERSION=16.15.0"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/homebridge/node_modules/.bin"
      - "QEMU_ARCH=arm"
      - "S6_OVERLAY_VERSION=2.2.0.3"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_KEEP_ENV=1"
      - "USER=root"
      - "HOMEBRIDGE_APT_PACKAGE=1"
      - "UIX_CUSTOM_PLUGIN_PATH=/var/lib/homebridge/node_modules"
      - "HOME=/home/homebridge"
      - "npm_config_prefix=/opt/homebridge"
      - "HOMEBRIDGE_PKG_VERSION=1.0.33"

    expose:
      - "8581/tcp"

    hostname: "atlaspi"

    image: "oznu/homebridge:latest"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "e1753b165cdceadd2cfaa735d8832e8c4c091dab4f47ef49d2505a315c94e8d3"
      com.docker.compose.container-number: "1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "homebridge"
      com.docker.compose.project.config_files: "/data/compose/11/docker-compose.yml"
      com.docker.compose.project.working_dir: "/data/compose/11"
      com.docker.compose.service: "homebridge"
      com.docker.compose.version: "2.0.0"
      org.opencontainers.image.authors: "oznu"
      org.opencontainers.image.description: "Official Homebridge Docker Image"
      org.opencontainers.image.licenses: "GPL-3.0"
      org.opencontainers.image.title: "Homebridge in Docker"
      org.opencontainers.image.url: "https://github.com/oznu/docker-homebridge"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    restart: "always"

    volumes:
      - "/data/compose/11/config:/homebridge"

    working_dir: "/homebridge"

  transmission:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "transmission"

    entrypoint:
      - "/init"

    environment:
      - "HOME=/root"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PGID=1000"
      - "PS1=$(whoami)@$(hostname):$(pwd)\\$"
      - "PUID=1000"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "S6_VERBOSITY=1"
      - "TERM=xterm"
      - "TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true"
      - "TZ=Europe/London"

    hostname: "atlaspi"

    image: "ghcr.io/linuxserver/transmission:3.00-r8-ls151"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 3.00-r2-ls85 Build-date:- 2021-04-15T13:20:47+00:00"
      com.docker.compose.config-hash: "f7e2cfac9268bc94db18bb007900a1dab503a0c6b9ab752165afe271aa24a0f6"
      com.docker.compose.container-number: "1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "compose"
      com.docker.compose.project.config_files: "docker-compose.yml,docker-compose.override.yml"
      com.docker.compose.project.working_dir: "/home/pi/.docker/compose"
      com.docker.compose.service: "transmission"
      com.docker.compose.version: "1.28.0"
      maintainer: "aptalca"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2023-02-15T14:46:07+01:00"
      org.opencontainers.image.description: "[Transmission](https://www.transmissionbt.com/) is designed\
        \ for easy, powerful use. Transmission has the features you want from a BitTorrent client: encryption,\
        \ a web interface, peer exchange, magnet links, DHT, µTP, UPnP and NAT-PMP port forwarding, webseed\
        \ support, watch directories, tracker editing, global and per-torrent speed limits, and more."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-transmission"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "b093343809c4816318875eedc43bc4aa568c6516"
      org.opencontainers.image.revision: "b093343809c4816318875eedc43bc4aa568c6516"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-transmission"
      org.opencontainers.image.title: "Transmission"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-transmission/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "4.0.0-r6-ls155"

    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"

    networks:
      - "compose_default"

    ports:
      - "51413:51413/tcp"
      - "51413:51413/udp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
      - "9091:9091/tcp"

    restart: "unless-stopped"

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/pi/.config/appdata/transmission:/config"
      - "/home/pi/storage:/storage"
      - "/mnt/nas/Public/Downloads/watch:/watch"
      - "/mnt/nas/Public/Downloads:/downloads"

    working_dir: "/"

version: "3.6"                                                                                                                                [18:54:06]