version: "3.6"
services:
  tautulli:
    image: "linuxserver/tautulli:latest"
    ports:
      - "8181:8181/tcp"
    volumes:
      - "tautulli-config:/config"
      - "tautulli-logs:/logs"
    restart: "unless-stopped"

volumes:
  tautulli-config:
    external: true
  tautulli-logs:
    external: true
