version: "3.6"
services:
  uptime-kuma:
    image: "louislam/uptime-kuma:1"
    ports:
      - "3001:3001/tcp"
    restart: "always"
    volumes:
      - "uptime-kuma:/app/data"

volumes:
  uptime-kuma:
    external: true