- name: Basic set up of a new rpi with dist updates and basic installs
  hosts: "rpi_build"
  become: yes
  tasks:
    - name: install required system packages
      apt:
        pkg:
          - aptitude
          - zsh
          - wget
          - git
          - curl
          - mosh
        state: latest
        update_cache: true

    # Set up admin scripts / logging
    - name: create bin directory
      file:
        path: /home/pi/bin
        state: directory
        owner: pi
        group: pi
        mode: '0774'

    - name: create log directory
      file:
        path: /home/pi/log
        state: directory
        owner: pi
        group: pi
        mode: '0774'

    - name: copy server admin files
      copy:
        src: "{{ item }}"
        dest: /home/pi/bin
        owner: pi
        group: pi
        mode: '0755'
      with_fileglob: "{{ scripts }}/server_*" # Path needs updating/fixing

    # Update Crontab with auto updates
    - name: Create the auto update schedule
      ansible.builtin.cron:
        name: "configure server_update.sh"
        user: pi
        weekday: "6"
        minute: "0"
        hour: "6"
        job: "/home/pi/bin/server_update.sh>/home/pi/log/update.log 2>&1"

    # Update authorized keys file
    - name: copy authorized keys
      copy:
        src: "{{ scripts }}/.authorized_keys"
        dest: /home/pi/bin
        owner: pi
        group: pi
        mode: '0755'

# Default pi build with default user and password now created. Hooray