- name: Deploy basic admin containers
  hosts: "rpi_build"
  tasks:
    # Deploy the portainer volume and container
    - name: create Portainer Volume
      community.docker.docker_volume:
        name: portainer-data
        recreate: never
        state: present

    - name: deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "portainer/portainer-ce:latest"
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: always

    # Deploy Watchtower
    - name: Deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: "containrrr/watchtower:latest"
        command: --schedule "0 0 4 * * *" --debug
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always

    # Deploy Dockge
    - name: Deploy Dockge
      community.docker.docker_container:
        name: Dockge
        image: louislam/dockge:latest
        ports:
          - "5001:5001"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/pi/data:/app/data
          - /home/pi/stacks:/home/pi/stacks
        env:
          DOCKGE_STACKS_DIR: "/home/pi/stacks"
        restart_policy: always
