- name: Build the Atlas Docker stack
  hosts: "rpi_build"
  tasks:
    # Copy compose files
    - name: copy compose files
      copy:
        src: "{{ item }}"
        dest: /home/pi
        owner: pi
        group: pi
        mode: '0755'
      with_fileglob: "{{ compose }}/*_compose.yml"

    # TODO: Copy the remaining config files

    # Create the needed volumes for the monitor_compose
    - name: create Grafana Volume
      community.docker.docker_volume:
        name: grafana-storage
        recreate: never
        state: present

    - name: create Prometheus Volume
      community.docker.docker_volume:
        name: prometheus-storage
        recreate: never
        state: present

    - name: create Uptime-Kuma Volume
      community.docker.docker_volume:
        name: uptime-kuma
        recreate: never
        state: present

    # Run docker compose to set up the new containers
    - name: Deploy the monitor containers
      shell:
        cmd: 'docker compose -f monitor-compose.yml up'
