- name: Build the Atlas Docker stack
  hosts: "rpi_build"
  tasks:
    # Create a working directory
    - name: create work directory
      file:
        path: /home/pi/work
        state: directory
        owner: pi
        group: pi
        mode: '0774'

    # Copy compose files
    - name: copy compose files
      copy:
        src: "{{ item }}"
        dest: /home/pi/work
        owner: pi
        group: pi
        mode: '0755'
      with_fileglob: "{{ compose }}/*_compose.yml"

    # Copy template files
    - name: copy template files
      copy:
        src: "{{ item }}"
        dest: /home/pi/work
        owner: pi
        group: pi
        mode: '0755'
      with_fileglob: "{{ template }}/*.*"

    # TODO: Create the .config and sub directories ahead of container creation...

    # Create the needed volumes for the monitor_compose
    - name: create Grafana Volume
      community.docker.docker_volume:
        name: grafana-storage
        recreate: never
        state: present

    - name: create Prometheus Volume
      community.docker.docker_volume:
        name: prometheus-storage
        recreate: never
        state: present

    - name: create Uptime-Kuma Volume
      community.docker.docker_volume:
        name: uptime-kuma
        recreate: never
        state: present

    # Run docker compose to set up the new containers
    - name: Deploy the monitor containers
      shell:
        cmd: docker compose -f /home/pi/work/monitor_compose.yml up

    # Run docker compose to set up the new containers
    - name: Deploy the service containers
      shell:
        cmd: docker compose -f /home/pi/work/service_compose.yml up

    # Run docker compose to set up the new containers
    - name: Deploy the media containers
      shell:
        cmd: docker compose -f /home/pi/work/media_compose.yml up

    # TODO: update container files for transmission
    # TODO: Restore backups of homebridge, grafana and uptime kuma.
