- name: Build the Atlas Docker stack
  hosts: "rpi_build"
  become: yes
  tasks:
   # Install python and pip
    - name: install required system packages
      apt:
        pkg:
          - python3
          - python3-pip
        state: latest
        update_cache: true

    # Install and configure docker
    - name: Install docker
      ansible.builtin.raw: curl -sSL https://get.docker.com | sh

    - name: fiddle the docker socket permission
      ansible.builtin.raw: sudo chmod 666 /var/run/docker.sock

    # Install docker api with python3-pip
    - name: Install docker api
      ansible.builtin.raw: pip install docker

    # Install Portainer
    - name: create new volume
      community.docker.docker_volume:
        name: portainer-data
    
    - name: deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "portainer/portainer-ce:latest"
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: always

    # Install Watchtower
    - name: Deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: "containrrr/watchtower:latest"
        command: --schedule "0 0 4 * * *" --debug
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always
    
    # Final Steps go here: Change the hostnames and reboot the system.
    - name: Set a hostname specifying strategy
      ansible.builtin.hostname:
        name: AtlasPi
        use: debian
    
     # TODO: change default password here
