- name: Build the Atlas Docker stack
  hosts: "rpi_build"
  tasks:
   # Install python
    - name: install Python3
      become: yes
      apt:
        name: python3
        state: latest
        update_cache: true

   # Install PIP
    - name: install python3-pip
      become: yes
      apt:
        name: python3-pip
        state: latest
        update_cache: true

   # Install docker SDK
    - name: install python3-docker
      become: yes
      apt:
        name: python3-docker
        state: latest
        update_cache: true

    # Install and configure docker
    - name: Install docker
      shell:
        cmd: curl -sSL https://get.docker.com | sh

    - name: fiddle the docker socket permission
      shell:
        cmd: sudo chmod 666 /var/run/docker.sock

    # Create a working directory
    - name: create work directory
      file:
        path: /home/pi/work
        state: directory
        owner: pi
        group: pi
        mode: '0774'

    # Copy compose files
    - name: copy compose files
      copy:
        src: "{{ item }}"
        dest: /home/pi/work
        owner: pi
        group: pi
        mode: '0755'
      with_fileglob: "{{ compose }}/*_compose.yml"

    # Copy template files
    - name: copy template files
      copy:
        src: "{{ item }}"
        dest: /home/pi/work
        owner: pi
        group: pi
        mode: '0755'
      with_fileglob: "{{ template }}/*.*"

