- name: Build the Atlas Docker stack
  hosts: "rpi_build"
  tasks:
    # Install Portainer
    - name: create new volume
      community.docker.docker_volume:
        name: portainer-data
    
    - name: deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "portainer/portainer-ce:latest"
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: always

    # Install Watchtower
    - name: Deploy Watchtower
      community.docker.docker_container:
        name: watchtower
        image: "containrrr/watchtower:latest"
        command: --schedule "0 0 4 * * *" --debug
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: always
    
    # Install Node-exporter
    - name: Deploy node-exporter
      community.docker.docker_container:
        name: node-exporter
        image: "quay.io/prometheus/node-exporter:latest"
        command: --path.rootfs=/host
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /:/host
        restart_policy: always
