- name: Build the Atlas Docker stack
  hosts: "rpi_build"
  tasks:
   # Install python
    - name: install Python3
      apt:
        name: python3
        state: latest
        update_cache: true

   # Install PIP
    - name: install python3-pip
      apt:
        name: python3-pip
        state: latest
        update_cache: true

   # Install docker SDK
    - name: install python3-docker
      apt:
        name: python3-docker
        state: latest
        update_cache: true

    # Install and configure docker
    - name: Install docker
      shell:
        cmd: curl -sSL https://get.docker.com | sh

    - name: fiddle the docker socket permission
      shell:
        cmd: sudo chmod 666 /var/run/docker.sock
