- name: Basic set up of a new rpi with dist updates and basic installs
  hosts: "{{ variable_host }}"
  become: yes
  tasks:
    # Start tasks with the basic os upgrades
    - name: basic os upgrade
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: install required packages
      apt:
        name:
          - zsh
          - wget
          - git
        state: present
        update_cache: true
    - name: create bin directory
      file:
        path: /home/pi/bin
        state: directory
        mode: '0644'
    - name: create log directory
      file:
        path: /home/pi/log
        state: directory
        mode: '0644'
    - name: copy server admin files
      copy:
        src: "{{ item }}"
        dest: /home/pi/bin
        owner: pi
        group: pi
        mode: '755'
      with_fileglob: "~/Code/Unix/Pi_Files/General/server_*"
    - name: change user shell to zsh
      user:
        name: pi
        shell: /usr/bin/zsh
    #TODO: Install oh-my-zsh?
    - name: copy zsh config
      copy:
        src: "{{ item }}"
        dest: /home/pi
        owner: pi
        group: pi
        mode: '644'
      with_fileglob: "~/Code/Unix/Pi_Files/General/config/.z*"
    - name: Create the auto update schedule
      ansible.builtin.cron:
        name: "configure server_update.sh"
        user: pi
        weekday: "6"
        minute: "0"
        hour: "6"
        job: "/home/pi/bin/server_update.sh>/home/pi/log/update.log 2>&1"