- name: Install and cofigure zsh
  hosts: "rpi_build"
  tasks:
    # Make sure Zsh is installed
    - name: Install ZSH
      apt:
        name: zsh
        state: latest

    # Change shell to zsh and configure
    - name: change user shell to zsh
      become: yes
      user:
        name: pi
        shell: /usr/bin/zsh

    # Install oh-my-zsh (now works)
    - name: Install oh-my-zsh
      shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

    - name: copy zsh config
      copy:
        src: "{{ item }}"
        dest: /home/pi
        owner: pi
        group: pi
        mode: '644'
      with_fileglob: "{{ scripts }}/config/.z*" # Path need updating
      