- name: Finalise the atlas build
  hosts: "rpi_build"
  become: yes
  tasks:
    # Final Steps
    # TODO: Change the hostnames and reboot the system.
    - name: Set a hostname specifying strategy
      ansible.builtin.hostname:
        name: AtlasPi
        use: debian
    
    # TODO: change default password

    # TODO: Last step - server reboot to update hosts and redo mount points
    - name: reboot the server
      reboot: