- name: Deploy Service containers
  hosts: "rpi_build"
  tasks:
    # Create any required pi level files

    # Deploy required data volumes
    - name: create Calibreweb config Volume
      community.docker.docker_volume:
        name: calibreweb-config
        recreate: never
        state: present

    - name: create Calibreweb storage Volume
      community.docker.docker_volume:
        name: calibreweb-storage
        recreate: never
        state: present

    - name: create Plex config Volume
      community.docker.docker_volume:
        name: plex-config
        recreate: never
        state: present

    - name: create Plex storage Volume
      community.docker.docker_volume:
        name: plex-storage
        recreate: never
        state: present

    - name: create Tautulli config Volume
      community.docker.docker_volume:
        name: tautulli-config
        recreate: never
        state: present

    - name: create Tautulli logs Volume
      community.docker.docker_volume:
        name: tautulli-logs
        recreate: never
        state: present

    - name: create Audiobookshelf config Volume
      community.docker.docker_volume:
        name: audiobookshelf-config
        recreate: never
        state: present

    - name: create Audiobookshelf metadata Volume
      community.docker.docker_volume:
        name: audiobookshelf-metadata
        recreate: never
        state: present

    # Deploy The Containers!    
    - name: deploy calibreweb container
      community.docker.docker_container:
        name: calibreweb
        image: "ghcr.io/linuxserver/calibre-web:latest"
        ports:
          - "8083:8083"
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "calibreweb-config:/config"
          - "calibreweb-storage:/storage"
          - "/mnt/nas/Media/Calibre Library:/books"
        restart_policy: unless-stopped

    - name: deploy plex container
      community.docker.docker_container:
        name: plex
        image: "ghcr.io/linuxserver/plex:latest"
        ports:
          - "1900:1900/udp"
          - "3005:3005/tcp"
          - "32400:32400/tcp"
          - "32410:32410/udp"
          - "32412:32412/udp"
          - "32413:32413/udp"
          - "32414:32414/udp"
          - "32469:32469/tcp"
          - "33400:33400/tcp"
          - "8324:8324/tcp"
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "plex-config:/config"
          - "plex-storage:/storage"
          - "/mnt/nas/Media:/data"
        restart_policy: unless-stopped

    - name: deploy tautulli container
      community.docker.docker_container:
        name: tautulli
        image: "linuxserver/tautulli:latest"
        ports:
          - "8181:8181/tcp"
        volumes:
          - "tautulli-config:/config"
          - "tautulli-logs:/logs"
        restart_policy: unless-stopped

    - name: deploy audiobookshelf container
      community.docker.docker_container:
        name: audiobookshelf
        image: "ghcr.io/advplyr/audiobookshelf:latest"
        ports:
          - "13378:80"
        volumes:
          - /mnt/nas/Media/Audiobooks:/audiobooks
          - /mnt/nas/Media/Podcasts:/podcasts
          - audiobookshelf-config:/config
          - audiobookshelf-metadata:/metadata
        restart_policy: unless-stopped

    # TODO: Restore backups of homebridge, grafana and uptime kuma.