#based off the hosts.ini file
# Not currently working for multi?
all:
  hosts:
    localhost
  children:
    atlas:
      hosts:
        192.168.4.201
    pihole:
      hosts:
        192.168.4.202
    retropi:
      hosts:
        192.168.4.151
    multi:
      children:
        hosts:
          atlas
          pihole
          retropi
        vars:
          ansible_user=pi
