services:
  dockge:
    container_name: dockge
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/data:/app/data
      - /home/pi/stacks:/home/pi/stacks
    environment:
      - DOCKGE_STACKS_DIR=/home/pi/stacks
version: "3.6"
volumes:
  portainer-data:
    external: true
  sync-config:
    external: true
  sync-downloads:
    external: true
networks: {}
